### ISSUE TITLE
Superbooga: Cannot return the results in a contigious 2D array. Probably ef or M is too small

### ISSUE THREAD

**Issue by vbwright** [oobabooga/text-generation-webui#1909] opened 2023-05-08 12:11 UTC
### Describe the bug

Superbooga: When using any data input, "Cannot return the results in a contigious 2D array. Probably ef or M is too small."

MetaIX_GPT4-X-Alpasta30b-4bit
Instruct mode
Alpaca prompt

Input chunks loaded:  10
Chunk length:  500
Chunk count:  10
Max tokens:  1-2000

Found relevant report for langchain to provide more descriptive error:  https://github.com/hwchase17/langchain/pull/1149

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Set chunk length, chunk count, or max tokens outside of unspecified range from any data input source in Superbooga.

### Logs

```shell
Traceback (most recent call last):
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/mnt/tank/AGI/text-generation-webui/modules/text_generation.py", line 164, in generate_reply
    question = apply_extensions('input', question)
  File "/mnt/tank/AGI/text-generation-webui/modules/extensions.py", line 132, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/mnt/tank/AGI/text-generation-webui/modules/extensions.py", line 58, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
  File "/mnt/tank/AGI/text-generation-webui/extensions/superbooga/script.py", line 150, in input_modifier
    results = collector.get(user_input, n_results=chunk_count)
  File "/mnt/tank/AGI/text-generation-webui/extensions/superbooga/script.py", line 55, in get
    result = self.collection.query(query_texts=search_strings, n_results=n_results, include=['documents'])['documents'][0]
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 203, in query
    return self._client._query(
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/chromadb/api/local.py", line 247, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 521, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/home/quietday/miniconda3/envs/textgen/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 248, in get_nearest_neighbors
    database_labels, distances = self._index.knn_query(query, k=k, filter=filter_function)
RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is too small
```

### System Info

```shell
Ubuntu 22.04, Linux 6.2.6-76060206-generic
Latest 7 May 2023 pulls

text-generation-ui(main)
9754d6a8119a4c48226d40f69fe83d9f03079016

GPTQ-for-LLaMa(triton)
dfbf9a94b7426ea36051fd4146a7602ca461d235
```

**Comment by oobabooga** [comment] 2023-05-08 14:07
This sometimes happens to me, it seems to be caused by the user input not matching enough chunks sufficiently well. I don't know how to fix it, maybe someone can help

**Comment by kaiokendev** [comment] 2023-05-08 20:46
I think this is due to k > num_results in the index. It can be fixed by taking the min of k and elements in the index than using k directly. In this case, min of `len(self.ids)` and `n_results` in the `ChromaCollector`

**Closed** 2023-05-09 00:16 UTC
Labels: bug
