### ISSUE TITLE
Increase the temperature limit up to 10?

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#5088] opened 2023-12-27 00:51 UTC
Hello,

On this webUI the limit of temperature is 1.99, I was fine with that until I used Mixtral-Instruct (which is a really really confident finetuned model), I changed the script a bit and until a temp up to 10, it was working quite well, it really improved its creativity.

**Example 1:** She was a woman of...
![image](https://github.com/oobabooga/text-generation-webui/assets/110173477/763513ae-93b9-4616-a4ce-679e7b89aff6)
You can see that we really need to increase the temperature to get "equal" probability for all those viable tokens (as it should be when describing a woman in a good way, there's a lot of way to do it)

**Example 2:** You really get more interesting and creative output when you mix a high temperature with MinP, this text is for Temp = 9 + MinP = 0.05
![image](https://github.com/oobabooga/text-generation-webui/assets/110173477/987b148b-b684-4195-a218-7b79329ec012)

That's why I'm requesting that you'd up the temperature limit, thanks in advance for your response.

**Comment by oobabooga** [comment] 2024-01-05 01:32
That's a duplicate of https://github.com/oobabooga/text-generation-webui/issues/4952, and I have changed the upper limit to 5 here: https://github.com/oobabooga/text-generation-webui/commit/c9d814592e8463de2ed4c169e5ddafa9bbbd219d.

**Closed by oobabooga** 2024-01-05 01:32 UTC
Labels: enhancement
