### ISSUE TITLE
dockerize repo

### ISSUE THREAD

**Issue by loeken** [oobabooga/text-generation-webui#548] opened 2023-03-24 23:45 UTC
**Description**
I think having a Dockerfile/docker-compose config might be useful to avoid users having to deal with setting up their environments/testing/bug fixing.

**Additional Context**

I have created a PR: https://github.com/oobabooga/text-generation-webui/pull/547 it's just a basic PoC only covering nvida cards ( and only tested on a rtx 2060 so far )

**Comment by oobabooga** [comment] 2023-03-29 02:36
Duplicate of https://github.com/oobabooga/text-generation-webui/issues/174

**Closed by oobabooga** 2023-03-29 02:36 UTC
Labels: enhancement
