### ISSUE TITLE
API w/ ExLlama Unable to Generate Response in Certain Instances

### ISSUE THREAD

**Issue by HvskyAI** [oobabooga/text-generation-webui#2791] opened 2023-06-21 02:03 UTC
### Describe the bug

When using ooba API with ExLlama as the model loader, it appears to be unable to generate responses at certain points approaching maximum context length and returns one of two errors:

`RuntimeError: start (0) + length (2049) exceeds dimension size (2048).`

`RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`

This occurs only on certain responses. Notably, reloading the model via GPTQ-for-LLaMA generates a response as expected for the same instance. After generating a response for the specific instance that causes an issue, reloading model via ExLlama works without an issue from that point onwards. 

Updated both Text Generation Web UI and ExLlama to latest commits, but the issue persists. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load model via ExLlama
2. Connect API to frontend (e.g. SillyTavern)
3. Generate responses until the API throws above error
4. Reload model via alternative loader and confirm issue does not occur

Note: I'm not certain what causes certain instances to throw an error as opposed to others, which generate without an issue. 

### Logs

```shell
Traceback (most recent call last):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 294, in generate_reply_custom
    reply = shared.model.generate(question, state)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 86, in generate
    for output in self.generate_with_streaming(prompt, state):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 72, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 308, in gen_single_token
    logits = self.model.forward(self.sequence[:, -1:], self.cache, lora = self.lora)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\model.py", line 841, in forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\model.py", line 453, in forward
    self.self_attn.fused(hidden_states, cache, buffer, self.input_layernorm, lora)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\model.py", line 336, in fused
    key_states = cache.key_states[self.index].narrow(2, 0, past_len + q_len)
RuntimeError: start (0) + length (2049) exceeds dimension size (2048).
Output generated in 8.80 seconds (0.00 tokens/s, 0 tokens, context 1891, seed 335194999)
127.0.0.1 - - [21/Jun/2023 10:30:04] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 294, in generate_reply_custom
    reply = shared.model.generate(question, state)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 86, in generate
    for output in self.generate_with_streaming(prompt, state):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 72, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 317, in gen_single_token
    token, _ = self.sample(logits,
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 131, in sample
    sampled_ind = torch.multinomial(top_probs, top_probs.shape[-1] if num == -1 else min(num, top_probs.shape[-1]))
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 0.27 seconds (0.00 tokens/s, 0 tokens, context 1895, seed 84609728)
127.0.0.1 - - [21/Jun/2023 10:30:07] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 294, in generate_reply_custom
    reply = shared.model.generate(question, state)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 86, in generate
    for output in self.generate_with_streaming(prompt, state):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 72, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 317, in gen_single_token
    token, _ = self.sample(logits,
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 131, in sample
    sampled_ind = torch.multinomial(top_probs, top_probs.shape[-1] if num == -1 else min(num, top_probs.shape[-1]))
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 0.35 seconds (0.00 tokens/s, 0 tokens, context 1895, seed 1247655507)
127.0.0.1 - - [21/Jun/2023 10:30:10] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 294, in generate_reply_custom
    reply = shared.model.generate(question, state)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 86, in generate
    for output in self.generate_with_streaming(prompt, state):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 72, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 317, in gen_single_token
    token, _ = self.sample(logits,
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 131, in sample
    sampled_ind = torch.multinomial(top_probs, top_probs.shape[-1] if num == -1 else min(num, top_probs.shape[-1]))
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 26.17 seconds (0.00 tokens/s, 0 tokens, context 1895, seed 437958952)
127.0.0.1 - - [21/Jun/2023 10:30:41] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 294, in generate_reply_custom
    reply = shared.model.generate(question, state)
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 86, in generate
    for output in self.generate_with_streaming(prompt, state):
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama.py", line 72, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 317, in gen_single_token
    token, _ = self.sample(logits,
  File "D:\AI\LLaMA\oogabooga\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 131, in sample
    sampled_ind = torch.multinomial(top_probs, top_probs.shape[-1] if num == -1 else min(num, top_probs.shape[-1]))
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 0.50 seconds (0.00 tokens/s, 0 tokens, context 1895, seed 2087978915)
```

### System Info

```shell
Windows 10
Nvidia RTX 3090 
Local
```

**Comment by bdashore3** [comment] 2023-06-21 04:09
This happens for me as well. However, I consistently get the error unless I switch back to GPTQ. My system is:

```
Windows 11 (WSL)
Nvidia RTX 3060
Local
```

**Comment by bdashore3** [comment] 2023-06-21 05:14
After some testing, I no longer get this error with #2766 @HvskyAI can you please merge the branch and test on your end?

**Comment by HvskyAI** [comment] 2023-06-21 07:56
@bdashore3 I tried the branch. It appears to still be throwing the same error for me:

`RuntimeError: start (0) + length (2049) exceeds dimension size (2048).`

I was also able to replicate the issue on a different machine, running Windows 10 / RTX 3070 8GB / Local and also received the error above using latest commits.

Interesting to note is that rolling back my SillyTavern install to V1.6.8 appears to alleviate the issue. I was only able to replicate the issue by updating SillyTavern to the latest main branch on that particular machine, as well.

**Comment by Yiximail** [comment] 2023-06-21 13:04
Well, perhaps I know why.

The total number of tokens during its generation will be over 2048
You can try api in postman, after generate 2048 tokens, if you loader is `exllama`, `oobabooga` will throw this error everytime

This error could caused by the inconsistency the way calculates tokens between `SillyTavern`  and `oobabooga`
tokens calculated by `SillyTavern` are less than `oobabooga`, so `SillyTavern` prompt passed to `oobabooga` longer.

It is also possible that it is not related to `exllama`, but due to the inconsistency between the tokenizer used by `SillyTavern` and your model
`autoGPTQ` will automatically intercept the context length until it can be generated in full, so you never encounter this problem before
(like you send 1900 context, max_new_tokens 248, it will cut down to 1800 in context automatically. keep total in 2048)
but `exllama` will send all contexts whether or not the total length is exceeded

This problem may not be solved in `oobabooga` or `exllama`
`SillyTavern` needs to provide a place to configure the tokenizer, or a way to count tokens

**Comment by Yiximail** [comment] 2023-06-21 13:09
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/4f146a7f-4fca-4698-ad52-ba25fc122af9)

I used around 2000 tokens length context and let it generate 193 max_new_tokens

I tried it before and after you used exllama
before (didn't use exllama):
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/3ea2a409-99d2-4546-83cd-d82810933df3)
it cuted 2048 - 193 = 1855

after (use exllama):
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/08711a64-16d4-47f0-9291-fc0efbdbed45)
it didn't cut

**Comment by HvskyAI** [comment] 2023-06-21 13:45
@Yiximail Interesting, thank you very much for the insight. 

I see that as tokens are estimated in SillyTavern, a discrepancy in how tokens are calculated between SillyTavern and the backend is causing the total number of tokens to exceed 2048, and thus producing:

`RuntimeError: start (0) + length (2049) exceeds dimension size (2048).`

SillyTavern does offer a setting for configuring the tokenizer, dependent upon model:

![Tokenizer Menu](https://github.com/oobabooga/text-generation-webui/assets/136893546/bade7b77-781f-432d-88d6-d6beec7ce25d)

Some more information on this at the relevant documentation page:

https://docs.sillytavern.app/usage/core-concepts/advancedformatting/#tokenizer

I was utilizing the "Sentencepiece"  tokenizer as recommended for LLaMA models. It would appear that utilizing "None/Estimated" instead alleviates the issue of exceeding 2048 tokens total at the cost of some context length:

`Output generated in 9.24 seconds (19.49 tokens/s, 180 tokens, context 1647, seed 582802787)`

The loss of context based on a tokenizer that estimates is not ideal, but it at least functions for the time being. Perhaps this can be compensated via Token Padding as discussed in the documentation above. 

Thank you very much!

**Comment by bdashore3** [comment] 2023-06-21 14:41
I hope this can also provide more insight. @HvskyAI, I'd take a look at your formatting options inside of SillyTavern. Your context overflow may be happening because of using presets that are moreso meant for pygmalion rather than any old LLaMA model. In addition, the model itself is not broadcasting its config so SillyTavern doesn't know anything (like Cohee said).

Perhaps this can explain why I'm not getting these errors while you are still getting them. Again, I have to test more and see if I do get the exception with the stop token PR merged.

Here are my settings. I will also test with pygmalion 13B (and its own settings) when I get the time.
![Screenshot 2023-06-21 at 10 37 48 AM](https://github.com/oobabooga/text-generation-webui/assets/8082010/cf091f00-6ad6-4152-b845-272c240218fa)
![Screenshot 2023-06-21 at 10 38 16 AM](https://github.com/oobabooga/text-generation-webui/assets/8082010/57c75653-4c38-4ec3-a61a-48620e7cd314)

**Comment by HvskyAI** [comment] 2023-06-21 15:22
@Cohee1207 I see, thank you for the explanation. 

So as it stands, front ends such as SillyTavern are essentially blind to any modification that has been done to model-specific tokenizers, leading to the necessity for token estimation when not using precisely matched configurations (e.g. Base LLaMA w/ Sentencepiece). I was not aware this was the case - I'll keep it in mind when configuring things from now on. 



@bdashore3 I'm also using LLaMA-derived models, so the non-Pygmalion formatting section of the documentation would apply:

https://docs.sillytavern.app/usage/core-concepts/advancedformatting/

Do you find that having all of the AutoFormat Overrides engaged has a positive effect or some benefit?

I see that this effectively changes how various pieces of context are formatted and presented to the model in the prompt. Is this desirable for LLaMA-based models in general? Or is it rather dependent upon the specific model being used, requiring trial and error on a model-per-model basis. 

I personally haven't tried with them engaged, as I imagined the default prompt format was structured in a specific manner for a reason. I'd really appreciate any input on why you've chosen to modify the formatting.

**Comment by bdashore3** [comment] 2023-06-21 16:08
You can find a better explanation in my [character creation guide](https://rentry.co/kingbri-chara-guide#sillytavern-settings), but this boils down to undoing pygmalion formatting since it's extremely unique as is.

The main benefits involve better conversation with a character when using a LLaMA model. Hopefully this fixes your token context overflow. I'd highly recommend using the llama tokenizer as it'll give you the best results vs using no tokenizer.

**Closed** 2023-06-22 06:34 UTC
Labels: bug
