### ISSUE TITLE
Failed Launch

### ISSUE THREAD

**Issue by JamesKnight0001** [oobabooga/text-generation-webui#622] opened 2023-03-29 02:12 UTC
### Describe the bug

Every time I launched this programs I usually get an error:
```
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with details about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```
This happened after I updated this program.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I tried all methods and all steps on how to fix this error but none worked.

### Logs

```shell
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```

### System Info

```shell
Windows 10
GPU: ???
Ram: 20 Gig
Storage: 1TB
```

**Comment by oobabooga** [comment] 2023-03-29 02:13
Duplicate of https://github.com/oobabooga/text-generation-webui/issues/614

**Closed by oobabooga** 2023-03-29 02:13 UTC
Labels: bug
