### ISSUE TITLE
Generates gibberish starting with a comma (when using 3090)

### ISSUE THREAD

**Issue by reidsanders** [oobabooga/text-generation-webui#930] opened 2023-04-08 21:25 UTC
### Describe the bug

It generates irrelevant gibberish starting with a comma.
See https://www.reddit.com/r/Oobabooga/comments/12ez276/3060_vs_3090_same_model_and_presets_but_very/

`CUDA SETUP: Detected CUDA version 121`

As recommended in that thread reverting to old commit fixes:
> git checkout 5f4f38ca5d11bd1739c0b99e26bb644637a04e0a
> pip install -r requirements.txt
> pip install protobuf==3.20

I could not find any combination of settings that worked. I have not tested with a different gpu, but according to the reddit thread this bug does not appear on a 3060.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run standard install as of cb169d0834
>python server.py --load-in-8bit
click generate with default settings.
```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Write a poem about the transformers Python library. 
Mention the word "large language models" in that poem.
### Response:
, and I'm not sure if it's appropriate to share this information with you.
I am not sure if it's appropriate to share this information with you.
Please let me know if you have any questions or concerns.
```

### Logs

```shell
Output generated in 12.43 seconds (3.94 tokens/s, 49 tokens, context 59)
```

### System Info

```shell
32 × AMD Ryzen 9 3950X 16-Core Processor
GPU: RTX 3090
5.15.104-2-MANJARO (64-bit)
```

**Comment by oobabooga** [comment] 2023-04-08 22:24
Duplicate of https://github.com/oobabooga/text-generation-webui/issues/931

**Closed by oobabooga** 2023-04-08 22:24 UTC
Labels: bug
