### ISSUE TITLE
VRAM keeps being used on unload or change the model when using exllama.

### ISSUE THREAD

**Issue by Panchovix** [oobabooga/text-generation-webui#2750] opened 2023-06-18 18:40 UTC
### Describe the bug

Hi there, the issue is pretty straighforward. When loading a model with exllama, and then wanting to change the model to other or unloading the model, the VRAM doesn't go down. This means that the only way to change the model is restarting the webui completely to get the VRAM back.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load a model in the webui using exllama. Aiming to get near full VRAM.
2. Try to change the model to another one.
3. Get torch.cuda.OutOfMemoryError: CUDA out of memory.

### Logs

```shell
2023-06-18 04:12:11 INFO:Loading TheBloke_airoboros-65B-gpt4-1.2-GPTQ...
2023-06-18 04:12:24 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\server.py", line 73, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 277, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\exllama.py", line 41, in from_pretrained
    model = ExLlama(config)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 630, in __init__
    tensor = tensor.to(device, non_blocking = True)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.99 GiB is allocated by PyTorch, and 23.95 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\server.py", line 1034, in <module>
    time.sleep(0.5)
KeyboardInterrupt
¿Desea terminar el trabajo por lotes (S/N)? s
PS F:\ChatIAs\oobabooga\bats\bats\password\exllama> & '.\start-webui - 2 gpus - exllama.bat'
```

### System Info

```shell
Windows 11
RTX 4090 x2
AMD Ryzen 7 7800X3D
64GB DDR5
```

**Comment by oobabooga** [comment] 2023-06-18 19:48
Duplicate of https://github.com/oobabooga/text-generation-webui/issues/2743, so I'm closing this one.

**Closed by oobabooga** 2023-06-18 19:48 UTC
Labels: bug
