### ISSUE TITLE
new out of memory issue (possible regression?)

### ISSUE THREAD

**Issue by thot-experiment** [oobabooga/text-generation-webui#490] opened 2023-03-22 07:20 UTC
### Describe the bug

Trying to load llama-30B-q4 on Win 10, 64Gb ram, GV100 32Gb. I had gotten similar errors in the past but only intermittently, now I cannot load 30B at all. Feels like this is likely a bug even if it's not a regression but rather caused by some change on my end as the loading could use a disk cache if there isn't enough ram (right?)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Unsure. Just running the program and trying to load 30b same as yesterday.

### Logs

```shell
Starting the web UI...
Loading llama-30b-hf...
Loading model ...
Traceback (most recent call last):
  File "d:\ooba\text-generation-webui\server.py", line 241, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "d:\ooba\text-generation-webui\modules\models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "d:\ooba\text-generation-webui\modules\GPTQ_loader.py", line 64, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "d:\ooba\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 245, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "d:\ooba\installer_files\env\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "d:\ooba\installer_files\env\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "d:\ooba\installer_files\env\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "d:\ooba\installer_files\env\lib\site-packages\torch\serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 425984001 bytes.
```

### System Info

```shell
EPYC 7542
64Gb ram
GV100
Win10
```

**Comment by thot-experiment** [comment] 2023-03-22 07:34
Just successfully launched, changed nothing just ran the script again on the off chance it would work. ¯\_(ツ)_/¯

**Comment by PeterDaGrape** [comment] 2023-03-22 08:53
Got this too, if anyone finds a fix lmk

**Comment by RandomInternetPreson** [comment] 2023-03-22 11:49
You will get this error if you have a ramdisk or virturaldisk running prior to loading your model.  You can set up your ramdisk after you load the model though.

**Comment by PeterDaGrape** [comment] 2023-03-22 11:54
Im sorry but I havent heard of either

**Comment by PeterDaGrape** [comment] 2023-03-22 12:23
I have to use swap space on my drive, because i only have 8GB Ram, also loading any model in regular mode results in python just crashing

**Comment by oobabooga** [comment] 2023-03-29 02:49
Duplicate of https://github.com/oobabooga/text-generation-webui/issues/490

Closing as the problem has been solved for the original poster

**Closed by oobabooga** 2023-03-29 02:49 UTC
Labels: bug

**Comment by thot-experiment** [comment] 2023-03-30 10:13
fwiw I still occasionally get this, it was always intermittent and it seems to be better now, but it does still happen from time to time, i just bumped to the latest commit, i'll keep this thread posted if it happens again
