### ISSUE TITLE
Add Bark TTS support

### ISSUE THREAD

**Issue by YakuzaSuske** [oobabooga/text-generation-webui#1549] opened 2023-04-26 00:46 UTC
**Description**
Bark is the new TTS and i think we would benefit from getting a TTS extension or implementation of Bark. I have played around with Bark locally on my pc and it's quite fun and sometimes realistic, almost Eleven labs level in rare cases. Tho there are some issues and fixes that would need to be implemented. The software currently by default can do a max of 15 seconds of audio, tho there is a repo that uses a code that instead cuts the prompts into pieces and basically stitches those together to make the audio longer than 15 seconds. More info on Bark below. Currently the best sounding female voice and the most natural is "en_speaker_8". The software also has voice cloning capabilities but due to misuse and etc it has been locked. Tho there is a group that managed to jailbreak it into implementing the voice cloning feature.

**Additional Context**
Original repo:
https://github.com/suno-ai/bark

The Webui that i'm using:
 https://github.com/Fictiverse/bark
 
 The repo with the longer than 15 seconds limit:
 https://github.com/JonathanFly/bark
 
 Jailbroken with Voice cloning:
 https://github.com/serp-ai/bark-with-voice-clone
 
 Voice cloning on hugging face:
 https://huggingface.co/spaces/fffiloni/clone-voice-for-bark
 
 More info on installation here:
 https://youtu.be/w41-MUfxIWo

**Comment by YakuzaSuske** [comment] 2023-04-26 00:50
Audio generated using Bark, (Avatar related):
https://drive.google.com/file/d/1cvJuFHJHZFzdqxlRdn_oOjcoSDYT7hT8/view?usp=sharing

Note: You might hear duplicate voice lines, that's because i was testing different prompts.

**Comment by Radtoo** [comment] 2023-04-26 00:52
Probably a duplicate of #1423

Currently you can try these:
https://github.com/wsippel/bark_tts
https://github.com/minemo/text-generation-webui-barktts

**Comment by YakuzaSuske** [comment] 2023-04-26 00:56
> Probably a duplicate of #1423
> 
> Currently you can try these: https://github.com/wsippel/bark_tts https://github.com/minemo/text-generation-webui-barktts

Lol i didn't see those. My bad.

**Closed** 2023-04-26 01:04 UTC
Labels: enhancement
