### ISSUE TITLE
sd_api_pictures: (1). No Default Mode Setting (2). Bad Metadata ("Denoising")

### ISSUE THREAD

**Issue by altoiddealer** [oobabooga/text-generation-webui#1316] opened 2023-04-17 14:46 UTC
### Describe the bug

Hello, for starters,  sd_api_pictures is an amazing extension which I'm very grateful for.
The recent update to retain SD's metadata was a huge improvement.

Two bugs to report at this time:

**(1). No Default Mode Setting**

According to the Script.py, the default Mode is a configurable default setting in settings.json.
However, it doesn't seem to have any effect when used as described.

If this is an error due to it being a dropdown menu, perhaps just make the mode radio buttons?

<img width="1151" alt="Mode" src="https://user-images.githubusercontent.com/1613484/232514879-8eb3d049-aef9-4dac-9926-54d1e9c679aa.png">

**(2). Bad Metadata** ("Denoising")

A typical txt2img Stable Diffusion generation, without highresfix enabled, does not contain a "Denoising" attribute in the metadata.  This allows you to send the image from PNG Info to txt2img, img2img, or anywhere else without affecting the Denoising setting in the UI.

However, the generations using sd_api_pictures seem to always include a Denoising parameter in the metadata set at "0".
So, every image that is fed back into Stable Diffusion will modify the Denoising parameter.

This is a mildly annoying for single-instance cases of using the generated image as input in SD.
I imagine this would be extremely annoying for anyone using any sort of automated batch process (although there could possibly be some way to override the metadata?  No clue).

<img width="1163" alt="denoising" src="https://user-images.githubusercontent.com/1613484/232519147-2e3f7101-71bb-4a79-ade9-99bebd6350bc.png">

And here is an example of typical txt2img metadata without HiResFix:

<img width="1009" alt="typical" src="https://user-images.githubusercontent.com/1613484/232519686-5c0dccd7-ba7d-429a-a850-35098cbecfd3.png">

**ON THIS TOPIC - It would be super awesome if Restore Faces, HiResFix, and their applicable settings, were all integrated into the sd_api_pictures extension.**

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using latest commit of oobabooga

Issue 1:
use _"sd_api_pictures-mode": 2,_ in settings.json, as described in script.py
launch text generation web-UI
default mode setting is not applied

Issue 2:
Use any generated image via sd_api_pictures, as input for Stable Diffusion
Erroneous _Denoising = 0_ metadata will override default settings in Stable DIffusion.

### Screenshot

Provided in description

### Logs

```shell
N/A
```

### System Info

```shell
Windows 11, Gigabyte RTX 4070ti
```

**Comment by boricuapab** [comment] 2023-04-18 07:04
I also feel adding options for restore face and high res fixing in oobabooga would be great, right now my workflow is to take the generated image back to a1111 and upscale them using img2img

For example, this is the oobabooga  image

![REVAi_SDPromptEngineer_1681797520](https://user-images.githubusercontent.com/61924816/232697686-5f15f94d-fb7b-47db-9181-9f741cf4960a.png)

and this is upscaling it in a1111

![00001-2233930331](https://user-images.githubusercontent.com/61924816/232697847-e81d5de5-c055-4c7f-a378-7c7f77b4308d.png)

**Comment by altoiddealer** [comment] 2023-04-18 10:54
Very nice - I’m doing the same, except at least a dozen or so at a time, so it’s tedious to correct the Denoise value every time

**Comment by GuizzyQC** [comment] 2023-04-18 20:47
The denoise value issue I suspect is an API bug in Auto1111, as the text-generation-webui extension doesn't send the setting at all in the payload. With nothing set, the expected behavior for the API would be to use the current default setting instead of 0. If it were possible, we could circumvent this bug by fetching the current value and feeding it back again, but unfortunately looking at the API doc, I can't find a way to fetch the current denoise_strength. That means that the best solution we can reasonably implement on the text-generation-webui for now is to add to the payload a more sane default than 0; maybe 0.7 since that seems to be the default in Auto1111. Of course, eventually people are going to complain that this is overwriting their carefully selected denoise value. And once the API bug is fixed on the SD side, we would have to revert this change to match the expected behavior (that if you don't set it, it uses the current value).

How often do you figure people would change their setting for restore faces and hires? I'm genuinely curious here, I don't play with my SD settings much, but I'm also not a SD wizard. It would be totally possible to add these settings, they are in the API, but there's also a concern of not crowding the interface with every possible SD API setting. If it's something that people tend to set and leave as is, perhaps it's better adding it as just a parameter that can be set in the settings file. If it's often played with, then we should add a checkbox.

**Comment by Brawlence** [comment] 2023-04-19 13:32
@GuizzyQC I don't toggle 'Restore faces' and 'Hires Fix' at all; every batch is either with it enabled or disabled fully.

Additionally, to avoid overcrowding the interface, we could use yet another `Gr.accordion()`

**Comment by GuizzyQC** [comment] 2023-04-19 14:53
Yeah, I didn't use it either personally but now that I added it in my PR I do find it nice to have it. I checked the API Docs and added pretty much all the orphan settings we could add to the payload under the Generation Parameters accordion, for overcrowding it's not that bad.

**Comment by if-ai** [comment] 2023-04-19 15:20
I added all this in my pull request too

**Closed** 2023-04-21 20:49 UTC
Labels: bug

**Comment by boricuapab** [comment] 2023-04-22 08:16
Works great, thank you all.

Uploading oobaboogaHRResult.mp4…
