### ISSUE TITLE
Characters extension only loads cards for selected model after recent update

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#660] opened 2023-03-30 14:51 UTC
### Describe the bug

I recently updated from `a04b7cf2643a5950fc215deac7f76b4b31336a81` (about 3 days ago) to head at `f0fdab08d31d4c00e2e15c5871413ce847ca842b`, and found the behaviour of the "Characters" control seems to have changed.

Previously, I could:

1) Start Server
2) Open Browser
3) Expand Characters section
4) Click on a Character

The model and chat history would load, as expected

After updating,

1) Start Server
2) Open Browser
3) Expand Characters section
4) Click on a Character
* The model and character do not load!

To load a character, now i have to:

1) Start Server
2) Open Browser
3) Load a specific character on the Character tab
4) Switch back to the "Text Generation" tab
3) Expand Characters section
4) Click on a Character

Then the model loads.

Is this expected?  It seems like a bug.  If expected, perhaps only available cards should show under characters?

FWIW, I very much prefer the old behaviour, as it allows me to test prompts among different characters/contexts more easily.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

0) git pull (I'm at `f0fdab08d31d4c00e2e15c5871413ce847ca842b`)
1) Start Server
2) Open Browser
3) Expand Characters section
4) Click on a Character
* The model and character do not load!

### Screenshot

No screenshot necessary for this one

### Logs

```shell
No logs to show
```

### System Info

```shell
n/a
```

**Comment by bmoconno** [comment] 2023-03-30 15:00
This seems to be a duplicate of #640

I don't know if anyone is currently working on it.

**Comment by brandonj60** [comment] 2023-03-30 19:47
Someone made an open PR to fix it here
https://github.com/oobabooga/text-generation-webui/pull/664

**Closed** 2023-03-31 05:06 UTC
Labels: bug
