### ISSUE TITLE
Google Tanslater 

### ISSUE THREAD

**Issue by elcotek** [oobabooga/text-generation-webui#1237] opened 2023-04-15 14:48 UTC
### Describe the bug

If i activate the translator inside the interface and apply the change, i can't load/reaload any model in the model section. Then only a message appears that the model is being reloaded, but nothing else happens. Also, the --GPU Memory commandline settings are completely ignored when starting the GUI.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

If i activate the translator inside the interface and apply the change, i can't load/reaload any model in the model section. Then only a message appears that the model is being reloaded, but nothing else happens. Also, the --GPU Memory commandline settings are completely ignored when starting the GUI.

If the translator is already active when the interface is started, no more models are loaded and you only have the choice of deactivating the translator again in order to be able to load the model again. The Google Translater is currently completely unusable due to the bug

### Logs

```shell
There are no error messages related to the problem.
```

### System Info

```shell
RTX 2080 8GB, Tessla M40 24 GB, 32 GB, Rizen 7 3700 Win 10 Pro
```

**Comment by oobabooga** [comment] 2023-04-15 15:07
The second part of the issue should be fixed (gpu_memory being ignored). I couldn't reproduce the part of being unable to load models after selecting the google_translate extension.

**Comment by elcotek** [comment] 2023-04-15 15:12
Then this bug must come from browser cache or somthing others. Sorry then. Thanks You, for all the work you do into this Project!!

**Comment by elcotek** [comment] 2023-04-15 15:38
After your --GPU patch, the translater works again now. We can close this Issue for now

**Closed** 2023-04-15 15:39 UTC
Labels: bug
