### ISSUE TITLE
RuntimeError: cannot release un-acquired lock

### ISSUE THREAD

**Issue by rpalmerdev** [oobabooga/text-generation-webui#6125] opened 2024-06-14 19:56 UTC
### Describe the bug

Exception ignored in: <generator object generate_reply at 0x000001EE928FEF20>
Traceback (most recent call last):
  File "F:\AI_Dynamic\aOoba\text-generation-webui-main\modules\text_generation.py", line 44, in generate_reply
    shared.generation_lock.release()
RuntimeError: cannot release un-acquired lock

I'm getting this running Yi-34b 4.0bpw.exl2 using ExLlamav2_HF. Chat-Instruct mode. Seems to maybe happen when regenerating replies too much/too fast

I'm not a dev, but guessing it might be related to #6107 based on finding the closed issue #6106  It at least sounds similar to my issue and the timeline works out. 🤷

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1: Load (probably any) exl2 model using ExLlamav2_HF - I was using Yi-34b 4.0bpw.exl2
2: Chat for awhile and regenerate a bunch of replies.
3: Restart the WebUI until it happens again.

### Logs

```shell
Exception ignored in: <generator object generate_reply at 0x000001EE928FEF20>
Traceback (most recent call last):
  File "F:\AI_Dynamic\aOoba\text-generation-webui-main\modules\text_generation.py", line 44, in generate_reply
    shared.generation_lock.release()
RuntimeError: cannot release un-acquired lock
```

### System Info

```shell
Windows 11 - RTX 4090 - Locally
```

**Comment by zhoukezi** [comment] 2024-06-15 16:36
I encountered this problem and tried to figure out what happened. It seems that `release` may sometimes be called from another thread. The problem may be caused by the `yield` statement. When a generator generates a value, the control is returned to the caller, so subsequent execution of the generator may occur on another thread. A quick hack to fix this is to replace `RLock` with `Lock` in `server.py`.

**Comment by rpalmerdev** [comment] 2024-06-16 01:42
It seems to have worked from what I can tell so far. Much respect. Thank you!

**Comment by alfredwallace7** [comment] 2024-06-16 19:47
Same error encountered with the Qwen2 GGUF model, llama.cpp backend and RTX2060.
The RLock to Lock fix in server.py seems to work.

**Comment by Kaszebe** [comment] 2024-06-16 23:02
Same exact issue on Ubuntu 22.04, 4090 + 4080 + 3080. Happens on several different models. The most recent time was an EXL2 file of which I had more than enough VRAM to run.

**Comment by Hellisotherpeople** [comment] 2024-06-19 06:48
I'm getting this too. 4xA100s

**Comment by oobabooga** [comment] 2024-06-27 05:24
Closing as this should be solved in the main branch now.

**Closed by oobabooga** 2024-06-27 05:24 UTC
Labels: bug
