### ISSUE TITLE
chatglm-6b support

### ISSUE THREAD

**Issue by nailuoGG** [oobabooga/text-generation-webui#426] opened 2023-03-19 10:06 UTC
**Description**

I tried to use THUDM/chatglm-6b, but the following error occurred.

**Additional Context**

https://huggingface.co/THUDM/chatglm-6b

```shell
python download-model.py THUDM/chatglm-6b
```

```shell
ValueError: Loading models/chatglm-6b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

```shell
 % ls -l models/chatglm-6b
total 13422501
-rwxrwxrwx 1 root root        697  3月 19 11:15 config.json
-rwxrwxrwx 1 root root 1904491802  3月 19 11:16 pytorch_model-00001-of-00008.bin
-rwxrwxrwx 1 root root 1879731432  3月 19 11:17 pytorch_model-00002-of-00008.bin
-rwxrwxrwx 1 root root 1980385902  3月 19 11:19 pytorch_model-00003-of-00008.bin
-rwxrwxrwx 1 root root 1913294120  3月 19 11:20 pytorch_model-00004-of-00008.bin
-rwxrwxrwx 1 root root 1879722289  3月 19 11:21 pytorch_model-00005-of-00008.bin
-rwxrwxrwx 1 root root 1879731496  3月 19 11:22 pytorch_model-00006-of-00008.bin
-rwxrwxrwx 1 root root 1074103621  3月 19 11:23 pytorch_model-00007-of-00008.bin
-rwxrwxrwx 1 root root 1233126123  3月 19 11:23 pytorch_model-00008-of-00008.bin
-rwxrwxrwx 1 root root      33416  3月 19 11:23 pytorch_model.bin.index.json
-rwxrwxrwx 1 root root        416  3月 19 11:23 tokenizer_config.json
```

**Comment by oobabooga** [comment] 2023-03-19 23:10
Duplicate of #317

**Closed by oobabooga** 2023-03-19 23:10 UTC
Labels: enhancement

**Comment by nameless0704** [comment] 2023-03-21 05:55
I didn't get it. After reading the context of these two issues, does that mean seq2seq models are systematically unsupported? If not, how did you manage to solve this error? I got the same.

**Comment by MarkSchmidty** [comment] 2023-03-23 01:48
@nameless0704 Support is being added. An open issue means the issue is being worked on. This issue was closed because it is a duplicate of the open issue. The other issue is open because support is being added.
