### ISSUE TITLE
Install.bat critical libmamba,MicroMamba hook not found.

### ISSUE THREAD

**Issue by N0rule** [oobabooga/text-generation-webui#927] opened 2023-04-08 20:41 UTC
### Describe the bug

when I run the install.bat, it tries to install, then i get this error after downloading,and trying to install.

my path is: D:\oobabooga-windows

critical libmamba ������ ������� �� ����� ������������� � �������� ������������� ������� ��������.

MicroMamba hook not found.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Extract
Run Install.bat
Choose A
Wait

### Screenshot

![image](https://user-images.githubusercontent.com/30196774/230741676-2c119b1c-c562-45ff-a03e-30e03576dbd6.png)

### Logs

```shell
Transaction starting
msys2-conda-epoch                                    3.2kB @  42.5kB/s  0.1s
ca-certificates                                    146.6kB @   1.8MB/s  0.1s
pytorch-mutex                                        2.9kB @  34.2kB/s  0.1s
ucrt                                                 1.3MB @  12.0MB/s  0.1s
libdeflate                                         151.9kB @   1.2MB/s  0.0s
m2w64-gmp                                          743.5kB @   5.7MB/s  0.1s
pthreads-win32                                     144.3kB @   1.1MB/s  0.1s
ninja                                              279.2kB @   1.3MB/s  0.1s
xz                                                 217.8kB @ 993.0kB/s  0.1s
libsqlite                                          669.9kB @   2.7MB/s  0.1s
m2w64-gcc-libs                                     532.4kB @   1.8MB/s  0.1s
libpng                                             343.9kB @   1.1MB/s  0.1s
xorg-libxau                                         58.0kB @ 167.6kB/s  0.1s
openjpeg                                           237.1kB @ 673.2kB/s  0.1s
blas-devel                                          13.5kB @  35.4kB/s  0.0s
libxcb                                               1.3MB @   3.5MB/s  0.1s
openssl                                              7.5MB @  14.3MB/s  0.4s
liblapack                                            5.9MB @   8.1MB/s  0.4s
libcusolver                                         30.0kB @  18.9kB/s  1.1s
cuda-documentation                                  93.4kB @  54.4kB/s  1.3s
cuda-nvml-dev                                       87.4kB @  49.3kB/s  1.4s
git                                                 97.8MB @  54.6MB/s  1.8s
cuda-libraries                                       1.4kB @ 556.0 B/s  0.7s
cuda-cudart                                          1.4MB @ 559.9kB/s  1.8s
charset-normalizer                                  44.9kB @  17.1kB/s  0.1s
mpmath                                             438.3kB @ 163.9kB/s  0.1s
cuda-nsight-compute                                  1.3kB @ 494.0 B/s  1.1s
cffi                                               233.7kB @  85.4kB/s  0.1s
requests                                            56.9kB @  20.6kB/s  0.0s
jinja2                                             101.4kB @  36.4kB/s  0.1s
m2w64-libwinpthread-git                             31.9kB @  11.3kB/s  0.0s
sympy                                                4.8MB @   1.7MB/s  0.2s
libiconv                                           714.5kB @ 248.6kB/s  0.1s
cuda-compiler                                        1.3kB @ 459.0 B/s  1.1s
jpeg                                               289.4kB @  98.4kB/s  0.1s
libuv                                              370.3kB @ 125.9kB/s  0.1s
intel-openmp                                         2.2MB @ 751.2kB/s  0.2s
m2w64-gcc-libgfortran                              350.7kB @ 112.8kB/s  0.2s
lcms2                                              498.4kB @ 160.0kB/s  0.2s
libtiff                                              1.2MB @ 367.9kB/s  0.2s
tzdata                                             117.6kB @  37.3kB/s  0.0s
libhwloc                                             2.5MB @ 800.7kB/s  0.2s
libcblas                                             5.9MB @   1.8MB/s  0.5s
cuda-nvtx                                           43.9kB @   9.5kB/s  1.4s
libcusparse                                         13.8kB @   2.9kB/s  1.6s
libcublas                                           24.5kB @   5.0kB/s  1.7s
wheel                                               55.7kB @  11.3kB/s  0.1s
certifi                                            150.8kB @  30.1kB/s  0.1s
filelock                                            14.1kB @   2.8kB/s  0.1s
cuda-libraries-dev                                   1.4kB @ 207.0 B/s  2.1s
urllib3                                            112.5kB @  16.4kB/s  0.1s
mkl-include                                        778.6kB @ 110.1kB/s  0.2s
vc                                                  15.7kB @   2.2kB/s  0.0s
cuda-nvrtc-dev                                      15.0MB @   2.1MB/s  5.4s
libwebp-base                                       268.4kB @  37.6kB/s  0.0s
zstd                                               288.4kB @  40.2kB/s  0.0s
tbb                                                153.6kB @  19.9kB/s  0.5s
libnvjpeg-dev                                        1.9MB @ 248.6kB/s  3.1s
tk                                                   3.7MB @ 467.8kB/s  0.8s
blas                                                14.1kB @   1.8kB/s  0.1s
libblas                                              5.9MB @ 739.1kB/s  0.3s
pillow                                              46.2MB @   5.6MB/s  3.1s
libcurand                                            3.1kB @ 334.0 B/s  1.5s
python                                              15.9MB @   1.6MB/s  0.5s
pycparser                                          102.7kB @  10.4kB/s  0.2s
typing_extensions                                   31.3kB @   3.1kB/s  0.1s
markupsafe                                          25.9kB @   2.6kB/s  0.2s
brotlipy                                           339.9kB @  32.4kB/s  0.4s
torchvision                                          8.1MB @ 519.9kB/s  5.1s
vs2015_runtime                                     725.0kB @  46.2kB/s  0.1s
libffi                                              42.1kB @   2.6kB/s  0.2s
libxml2                                              1.6MB @  97.3kB/s  0.7s
pthread-stubs                                        6.4kB @ 385.0 B/s  0.3s
mkl-devel                                            7.5MB @ 428.9kB/s  0.7s
libnpp                                             292.8kB @  15.8kB/s  1.2s
cuda-cupti                                          10.6MB @ 548.2kB/s 11.5s
cuda-cuxxfilt                                      169.2kB @   8.6kB/s  1.1s
cuda-visual-tools                                    1.4kB @  66.0 B/s  0.9s
networkx                                             1.5MB @  70.6kB/s  0.1s
pyopenssl                                          128.1kB @   6.2kB/s  0.1s
python_abi                                           6.1kB @ 295.0 B/s  0.0s
bzip2                                              152.2kB @   7.3kB/s  0.0s
xorg-libxdmcp                                       67.9kB @   3.2kB/s  0.8s
libcurand-dev                                       51.5MB @   1.8MB/s 20.5s
cuda-nvdisasm                                       33.2MB @   1.1MB/s 21.7s
cuda-nvcc                                           46.3MB @   1.2MB/s 16.4s
pytorch-cuda                                         6.9kB @ 172.0 B/s  2.1s
idna                                                56.7kB @   1.4kB/s  0.4s
cryptography                                         1.1MB @  26.6kB/s  0.2s
m2w64-gcc-libs-core                                219.2kB @   5.4kB/s  0.5s
freetype                                           497.4kB @  12.1kB/s  0.1s
cuda-sanitizer-api                                  13.2MB @ 247.7kB/s 24.7s
cuda-nvprune                                       155.2kB @   2.8kB/s  1.1s
cuda-cudart-dev                                    712.0kB @  12.0kB/s  4.8s
pysocks                                             19.3kB @ 325.0 B/s  0.1s
lerc                                               194.4kB @   3.3kB/s  0.0s
liblapacke                                           5.9MB @  98.8kB/s  0.2s
cuda-nvprof                                          1.6MB @  26.5kB/s  1.4s
cuda-nvrtc                                          75.4MB @   1.1MB/s 1m:5.3s
pip                                                  1.4MB @  19.9kB/s  0.1s
torchaudio                                           5.9MB @  86.6kB/s  0.2s
libcufft                                             5.6kB @  81.0 B/s  0.7s
libnpp-dev                                         119.9MB @   1.1MB/s 41.6s
win_inet_pton                                        8.2kB @  73.0 B/s  0.1s
mkl                                                191.6MB @   1.7MB/s  3.3s
cuda-cuobjdump                                       2.6MB @  22.3kB/s  1.8s
cuda-tools                                           1.3kB @  11.0 B/s  1.7s
cuda-memcheck                                      187.0kB @   1.6kB/s  1.1s
setuptools                                         580.3kB @   4.9kB/s  0.1s
libnvjpeg                                            4.4kB @  36.0 B/s  0.8s
cuda-toolkit                                         1.4kB @  11.0 B/s  1.9s
cuda-command-line-tools                              1.4kB @  11.0 B/s  1.0s
libcusolver-dev                                     90.8MB @ 699.2kB/s 1m:8.9s
cuda-runtime                                         1.3kB @  10.0 B/s  0.8s
pytorch                                              1.3GB @   7.5MB/s 36.8s
libzlib                                             71.2kB @ 424.0 B/s  0.1s
cuda-nvvp                                          119.1MB @ 640.6kB/s 1m:3.1s
cuda-cccl                                            1.2MB @   6.6kB/s  1.3s
numpy                                                5.9MB @  31.5kB/s  0.5s
libcufft-dev                                       261.9MB @   1.3MB/s 2m:58.0s
nsight-compute                                     352.5MB @   1.7MB/s 2m:41.5s
libcublas-dev                                      300.3MB @   1.4MB/s 3m:10.9s
libcusparse-dev                                    154.8MB @ 653.0kB/s 1m:9.4s
[+] 4m:37.4s
Linking pytorch-mutex-1.0-cuda
Linking git-2.40.0-h57928b3_1
Linking ca-certificates-2022.12.7-h5b45459_0
Linking ucrt-10.0.22621.0-h57928b3_0
Linking msys2-conda-epoch-20160418-1
Linking mkl-include-2022.1.0-h6a75c08_874
Linking intel-openmp-2023.0.0-h57928b3_25922
Linking python_abi-3.10-3_cp310
Linking vs2015_runtime-14.34.31931-h4c5c07a_10
Linking m2w64-libwinpthread-git-5.0.0.4634.697f757-2
Linking m2w64-gmp-6.1.0-2
Linking vc-14.3-hb6edc58_10
Linking m2w64-gcc-libs-core-5.3.0-7
Linking pthreads-win32-2.9.1-hfa6e2cd_3
Linking libiconv-1.17-h8ffe710_0
Linking libdeflate-1.17-hcfcfb64_0
Linking lerc-4.0.0-h63175ca_0
Linking libwebp-base-1.3.0-hcfcfb64_0
Linking jpeg-9e-hcfcfb64_3
Linking openssl-3.1.0-hcfcfb64_0
Linking libffi-3.4.2-h8ffe710_5
Linking bzip2-1.0.8-h8ffe710_4
Linking ninja-1.11.1-h91493d7_0
Linking libuv-1.44.2-h8ffe710_0
Linking xz-5.2.6-h8d14728_0
Linking tk-8.6.12-h8ffe710_0
Linking libzlib-1.2.13-hcfcfb64_4
Linking libsqlite-3.40.0-hcfcfb64_0
Linking m2w64-gcc-libgfortran-5.3.0-6
Linking libxml2-2.10.3-hc3477c8_6
Linking zstd-1.5.2-h12be248_6
Linking libpng-1.6.39-h19919ed_0
Linking m2w64-gcc-libs-5.3.0-7
Linking libhwloc-2.9.0-h51c2c0f_0
Linking libtiff-4.5.0-hf8721a0_2
Linking freetype-2.12.1-h546665d_1
Linking xorg-libxdmcp-1.1.3-hcd874cb_0
Linking xorg-libxau-1.0.9-hcd874cb_0
Linking pthread-stubs-0.4-hcd874cb_1001
Linking tbb-2021.8.0-h91493d7_0
Linking openjpeg-2.5.0-ha2aaf27_2
Linking lcms2-2.15-ha5c8aab_0
Linking libxcb-1.13-hcd874cb_1004
Linking mkl-2022.1.0-h6a75c08_874
Linking mkl-devel-2022.1.0-h57928b3_875
Linking libblas-3.9.0-16_win64_mkl
Linking liblapack-3.9.0-16_win64_mkl
Linking libcblas-3.9.0-16_win64_mkl
Linking liblapacke-3.9.0-16_win64_mkl
Linking blas-devel-3.9.0-16_win64_mkl
Linking blas-2.116-mkl
Linking tzdata-2023c-h71feb2d_0
Linking cuda-documentation-11.7.50-0
Linking cuda-nvcc-11.7.64-0
warning  libmamba [cuda-nvcc-11.7.64-0] The following files were already present in the e:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking nsight-compute-2022.2.0.13-0
warning  libmamba [nsight-compute-2022.2.0.13-0] The following files were already present:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-nvml-dev-11.7.50-0
warning  libmamba [cuda-nvml-dev-11.7.50-0] The following files were already present in t:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking libcusparse-11.7.3.50-0
Linking libnpp-11.7.3.21-0
Linking libcusolver-11.3.5.50-0
Linking libcufft-10.7.2.50-0
Linking cuda-nvrtc-11.7.50-0
Linking cuda-cudart-11.7.60-0
Linking libcurand-10.2.10.50-0
Linking libnvjpeg-11.7.2.34-0
Linking libcublas-11.10.1.25-0
Linking cuda-nvprof-11.7.50-0
warning  libmamba [cuda-nvprof-11.7.50-0] The following files were already present in the:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-nvdisasm-11.7.50-0
warning  libmamba [cuda-nvdisasm-11.7.50-0] The following files were already present in t:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-nvtx-11.7.50-0
warning  libmamba [cuda-nvtx-11.7.50-0] The following files were already present in the e:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-memcheck-11.7.50-0
warning  libmamba [cuda-memcheck-11.7.50-0] The following files were already present in t:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-sanitizer-api-11.7.50-0
warning  libmamba [cuda-sanitizer-api-11.7.50-0] The following files were already present:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-cupti-11.7.50-0
warning  libmamba [cuda-cupti-11.7.50-0] The following files were already present in the :
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-cuxxfilt-11.7.50-0
warning  libmamba [cuda-cuxxfilt-11.7.50-0] The following files were already present in t:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-cuobjdump-11.7.50-0
warning  libmamba [cuda-cuobjdump-11.7.50-0] The following files were already present in :
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-nvprune-11.7.50-0
warning  libmamba [cuda-nvprune-11.7.50-0] The following files were already present in th:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-cccl-11.7.58-0
Linking cuda-nsight-compute-11.7.0-0
Linking libcusparse-dev-11.7.3.50-0
Linking libnpp-dev-11.7.3.21-0
Linking libcusolver-dev-11.3.5.50-0
Linking libcufft-dev-10.7.2.50-0
Linking cuda-nvrtc-dev-11.7.50-0
Linking libcurand-dev-10.2.10.50-0
Linking libnvjpeg-dev-11.7.2.34-0
Linking libcublas-dev-11.10.1.25-0
Linking cuda-libraries-11.7.0-0
Linking cuda-nvvp-11.7.50-0
warning  libmamba [cuda-nvvp-11.7.50-0] The following files were already present in the e:
    - LICENSE
    - build_env_setup.bat
    - conda_build.bat
    - metadata_conda_debug.yaml
Linking cuda-command-line-tools-11.7.0-0
Linking cuda-compiler-11.7.0-0
Linking cuda-cudart-dev-11.7.60-0
Linking cuda-runtime-11.7.0-0
Linking cuda-libraries-dev-11.7.0-0
Linking cuda-visual-tools-11.7.0-0
Linking cuda-tools-11.7.0-0
Linking cuda-toolkit-11.7.0-0
Linking python-3.10.9-h4de0772_0_cpython
Linking pytorch-cuda-11.7-h16d0643_3
Linking wheel-0.40.0-pyhd8ed1ab_0
Linking setuptools-67.6.1-pyhd8ed1ab_0
Linking pip-23.0.1-pyhd8ed1ab_0
Linking pycparser-2.21-pyhd8ed1ab_0
Linking win_inet_pton-1.1.0-pyhd8ed1ab_6
Linking charset-normalizer-3.1.0-pyhd8ed1ab_0
Linking idna-3.4-pyhd8ed1ab_0
Linking certifi-2022.12.7-pyhd8ed1ab_0
Linking mpmath-1.3.0-pyhd8ed1ab_0
Linking typing_extensions-4.5.0-pyha770c72_0
Linking networkx-3.1-pyhd8ed1ab_0
Linking filelock-3.11.0-pyhd8ed1ab_0
Linking pysocks-1.7.1-pyh0701188_6
Linking sympy-1.11.1-pyh04b8f61_3
Linking markupsafe-2.1.2-py310h8d17308_0
Linking pillow-9.4.0-py310hdbb7713_1
Linking numpy-1.24.2-py310hd02465a_0
Linking cffi-1.15.1-py310h628cb3f_3
Linking cryptography-40.0.1-py310h6e82f81_0
Linking brotlipy-0.7.0-py310h8d17308_1005
Linking jinja2-3.1.2-pyhd8ed1ab_1
Linking pyopenssl-23.1.1-pyhd8ed1ab_0
Linking urllib3-1.26.15-pyhd8ed1ab_0
Linking requests-2.28.2-pyhd8ed1ab_1
Linking pytorch-2.0.0-py3.10_cuda11.7_cudnn8_0
Linking torchvision-0.15.0-py310_cu117
Linking torchaudio-2.0.0-py310_cu117
Transaction finished
critical libmamba ������ ������� �� ����� ������������� � �������� ������������� ������� ��������.

MicroMamba hook not found.
Press any key to continue . . .
```

### System Info

```shell
Windows 11
1060 TI
r5 2600
16gb RAM
```

**Comment by JaiQiBoi** [comment] 2023-04-09 09:07
Have been encountering this same error when initializing the 'install', 'start-webui', and 'download model' bat files.
This only occurs after downloading everything the first time via the 'install' bat file.
Deleted everything, and have chosen a new folder location, and am running install from scratch to see if this fixes the issue.

**Comment by JaiQiBoi** [comment] 2023-04-09 09:48
Re-installing from scratch fixed this; no idea why.

**Comment by N0rule** [comment] 2023-04-09 12:14
Re-installed from scratch,still the same issue, i tried using https://github.com/oobabooga/one-click-installers but it didn't help
![image](https://user-images.githubusercontent.com/30196774/230771887-c8a914ab-e157-4f71-806f-f7e833072889.png)

**Comment by P1901947** [comment] 2023-04-09 12:47
Same problem, but with different gibberish like:

critical libmamba bh줸ժتrXASo Unicode riH��쪺rC

MicroMamba hook not found.

It seems that the problem is due to Unicode settings, but even though I have changed the OS language and the BOOT page language, it still does not work.

**Comment by Kholioso** [comment] 2023-04-09 16:00
I have similar issues. Micromamba doesn't install any packages at first, then I click the install.bat file and let it create the "installer_files" folder. It repeatedly says that Micromamba was not found, then I replace the micromamba file from 09.04.2023 with one from 07.04.2023 and suddenly it installs the 123, 3.4GB packages. 

Then I get the exact same error as you (critical libmamba). So I place the micromamba from 09.04.2023 back into the "installer_files" folder and remove the micromamba 07.04.2023 version and the "critical libmamba" error disappears. However, the MicroMamba hook is not found. I attempted to add Micromamba to the path variable on Windows, but it did not work. I changed the OS language and BOOT page lang, nothing works. 

And I did everything I did with full administrator rights, so there shouldn't be any issue there, nor are there any spaces in my directories. I even tried the step by step version with miniconda3 and that's a whole other fiasco.

**Comment by P1901947** [comment] 2023-04-10 11:54
After I change the OS language to English and reinstalled it, I find that the gibberish part should be like this:

> critical libmamba No mapping for the Unicode character exists in the target multi-byte code page.
> 
> MicroMamba hook not found.

But still don't know how to fix it.

**Comment by Decikingship** [comment] 2023-04-12 13:42
Solution found!!!
Open your control panel, go to Region -- Change Time Zone blablabla -- Click on Manage tab -- Change system regional settings -- Check Beta box
![image](https://user-images.githubusercontent.com/29721376/231476456-2a877f8f-425d-4e9e-b525-0faed3bc1bd8.png)

**Comment by N0rule** [comment] 2023-04-12 15:58
> Solution found!!! Open your control panel, go to Region -- Change Time Zone blablabla -- Click on Manage tab -- Change system regional settings -- Check Beta box -- Restart your computer ![image](https://user-images.githubusercontent.com/29721376/231476456-2a877f8f-425d-4e9e-b525-0faed3bc1bd8.png)

Can confirm,fixed it for me

**Comment by N0rule** [comment] 2023-04-13 19:01
> @N0rule I see you reopened the issue. If you or anyone else are still having trouble, you could try to use [my own one-click installer](https://github.com/oobabooga/one-click-installers/pull/21) which uses Miniconda instead of Micromamba. It's typically more stable and has wider support than Micromamba

Issue is fixed for me,but only using workaround,that was mentioned earlier,i leaved bug open,because someone might have same problem,and it's still not fixed in releases

**Comment by oobabooga** [comment] 2023-04-24 17:25
Closing as the micromamba installer has been replaced with the miniconda installer by @xNul

**Closed by oobabooga** 2023-04-24 17:25 UTC
Labels: bug
