### ISSUE TITLE
Output of pygmalion-6b model doesn't terminate (?)

### ISSUE THREAD

**Issue by catboxanon** [oobabooga/text-generation-webui#26] opened 2023-01-26 00:42 UTC
I tried using the example character and one of the example inputs from the [Huggingface discussion](https://huggingface.co/PygmalionAI/pygmalion-6b/discussions/8#63d15cae119416cdbe15ae2e), but for some reason, the current dev branch (SHA256 of `pytorch_model-00001-of-00002.bin` starts with `a2401367`) results in the output continuing indefinitely to fill the allowed tokens, and also doesn't make much sense either. This doesn't match the example in the Huggingface discussion, and I didn't see mention of it as a bug, so I'm not sure what the cause is. Example below.

![](https://user-images.githubusercontent.com/122327233/214727196-d4fa030a-112e-4611-8b2f-a0b90864676f.png)

Only command-line flag in use is `--chat`. The other versions of the model I tested (first commit and most recent on the main branch) don't have the issue, only the latest on the dev branch.

**Comment by oobabooga** [comment] 2023-01-26 00:44
To reproduce the outputs in the HuggingFace discussion, make sure to select the `Debug-deterministic` preset.

**Comment by oobabooga** [comment] 2023-01-26 01:01
For me it generates the same output with the dev version. It keeps generating further output because it doesn't stop at `<|endoftext|>` (it probably should)

![dev](https://user-images.githubusercontent.com/112222186/214731245-64ab523d-5b7b-468e-b1a7-ebf765356278.png)

**Comment by oobabooga** [comment] 2023-01-26 01:29
It should be fixed now. Thanks for reporting this, I had not realized this kind of broken output was a bug in the web UI.

![fixed](https://user-images.githubusercontent.com/112222186/214735130-cf3bf7ea-8290-4b83-80f9-be0424a881a8.png)

**Closed** 2023-01-26 01:50 UTC
Labels: bug
