### ISSUE TITLE
Llama module not found

### ISSUE THREAD

**Issue by Priestru** [oobabooga/text-generation-webui#887] opened 2023-04-07 15:57 UTC
### Describe the bug

Traceback (most recent call last):
  File "E:\LLaMA\oobabooga-windows\text-generation-webui\server.py", line 308, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\LLaMA\oobabooga-windows\text-generation-webui\modules\models.py", line 106, in load_model
    from modules.llamacpp_model_alternative import LlamaCppModel
  File "E:\LLaMA\oobabooga-windows\text-generation-webui\modules\llamacpp_model_alternative.py", line 9, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. call python server.py  --auto-devices --chat --threads 8
2. ggml model
3. >> ModuleNotFoundError: No module named 'llama_cpp'

### Logs

```shell
none
```

### System Info

```shell
Windows
```

**Comment by Priestru** [comment] 2023-04-07 16:01
I do have llama.cpp separately and it does load this very same model. But webui for some reason doesn't any more.

From llama.cpp
llama_model_load: loading tensors from 'E:\LLaMA\oobabooga-windows\text-generation-webui\models\ggml-vicuna-13b-4bit-rev1\ggml-vicuna-13b-4bit-rev1.bin'
llama_model_load: model size =  7759.40 MB / num tensors = 363
llama_init_from_file: kv self size  =  400.00 MB

**Comment by Priestru** [comment] 2023-04-07 16:23
i tried git pull, install, and pip install llama-cpp-python. Nothing help

**Comment by Priestru** [comment] 2023-04-07 16:39
E:\LLaMA\oobabooga-windows\text-generation-webui\modules>pip install llama-cpp-python
Requirement already satisfied: llama-cpp-python in c:\python311\lib\site-packages (0.1.25)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\python311\lib\site-packages (from llama-cpp-python) (4.5.0)

Yet it doesn't work. How do i make GUI notice llama_cpp?

**Comment by Priestru** [comment] 2023-04-07 16:59
Downgraded my llama_cpp to 1.2.3 as per instruction, but nothing changed

E:\LLaMA\oobabooga-windows>pip install llama-cpp-python==0.1.23
Requirement already satisfied: llama-cpp-python==0.1.23 in c:\python311\lib\site-packages (0.1.23)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\python311\lib\site-packages (from llama-cpp-python==0.1.23) (4.5.0)

**Comment by Priestru** [comment] 2023-04-07 17:01
Launched with arguments directly mention model
`
call python server.py  --auto-devices --chat --threads 8 --model ggml-vicuna-13b-4bit-rev1`

got same error as before. i even tried to reboot too, just in case

```
Traceback (most recent call last):
  File "E:\LLaMA\oobabooga-windows\text-generation-webui\server.py", line 308, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\LLaMA\oobabooga-windows\text-generation-webui\modules\models.py", line 106, in load_model
    from modules.llamacpp_model_alternative import LlamaCppModel
  File "E:\LLaMA\oobabooga-windows\text-generation-webui\modules\llamacpp_model_alternative.py", line 14, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
```

**Comment by Priestru** [comment] 2023-04-07 17:43
Okay i reversed part of commit in modules/models.py back to

        from modules.llamacpp_model import LlamaCppModel
        
   And now it works and loads and everything.

**Comment by Crimsonfart** [comment] 2023-04-07 18:08
I have exactly the same problem

**Comment by vadimkara** [comment] 2023-04-07 18:09
Same problem

**Comment by vandervoortj** [comment] 2023-04-07 19:21
[Here](https://github.com/oobabooga/text-generation-webui/commit/58ed87e5d9dd864e38d346274e6455a4a041e203#r107908336)

For now, you can reinsert the removed line from requirements.txt and redownload the requirements with pip and it will resume working. *Works on my machine

**Comment by Priestru** [comment] 2023-04-07 19:47
Make sure that you have Python 3.10 on Windows. Otherwise it's one trouble after another.

**Comment by dromeuf** [comment] 2023-04-07 19:57
Hi Priestru, I am working with last Ubuntu 22.04 LTS with Anaconda 2.4 env python 3.10.9
I was getting several errors and warnings resolved by installing the cudatoolkit package 11.3.1 with Anaconda.
I update requirements with : pip install -r requirements.txt --upgrade

but the same error ::

(textgen) pcdr :~/text-generation-webui$ python server.py --auto-devices --chat --wbits 4 --groupsize 128

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/pcdr/anaconda3/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 113
/home/pcdr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/pcdr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so...
The following models are available:

1. anon8231489123_vicuna-13b-GPTQ-4bit-128g
2. facebook_opt-1.3b

Which one do you want to load? 1-2

1

Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Traceback (most recent call last):
  File "/home/pcdr/text-generation-webui/server.py", line 308, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/pcdr/text-generation-webui/modules/models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "/home/pcdr/text-generation-webui/modules/GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
(textgen) dr@pcdr:~/text-generation-webui$

**Comment by Priestru** [comment] 2023-04-07 20:06
Until ooba fix it, we can help themselves by reversing this commit to models.py:

https://github.com/oobabooga/text-generation-webui/commit/03cb44fc8ca24c6458dbd25c31acd1e8cbdfcde2

**Comment by dromeuf** [comment] 2023-04-07 20:27
I added the 2 lines but I still have the error.

(textgen) dr@pcdr:~/text-generation-webui$ **git pull**
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 24 (delta 17), reused 24 (delta 17), pack-reused 0
Unpacking objects: 100% (24/24), 3.10 KiB | 528.00 KiB/s, done.
From https://github.com/oobabooga/text-generation-webui
   962e33d..5543a50  main       -> origin/main
Updating 962e33d..5543a50
Fast-forward
 css/chat.css                              |  5 +++++
 extensions/elevenlabs_tts/script.py       |  3 ++-
 extensions/llama_prompts/script.py        |  3 ++-
 extensions/sd_api_pictures/script.py      |  4 ++--
 extensions/silero_tts/script.py           |  1 +
 extensions/silero_tts/test_tts.py         |  1 -
 extensions/silero_tts/tts_preprocessor.py |  1 -
 extensions/whisper_stt/script.py          | 36 +++++++++++++-----------------------
 modules/chat.py                           |  2 +-
 server.py                                 |  4 ++--
 10 files changed, 28 insertions(+), 32 deletions(-)

(textgen) dr@pcdr:~/text-generation-webui$ more requirements.txt 

accelerate==0.18.0
bitsandbytes==0.37.2
datasets
flexgen==0.1.7
gradio==3.24.1
**llamacpp==0.1.11
llama-cpp-python==0.1.23**
markdown
numpy
peft==0.2.0
requests
rwkv==0.7.3
safetensors==0.3.0
sentencepiece
pyyaml
tqdm
git+https://github.com/huggingface/transformers

(textgen) dr@pcdr:~/text-generation-webui$ **pip install -r requirements.txt --upgrade**

(textgen) dromeuf@BITUITOS:~/text-generation-webui$ **python server.py --auto-devices --chat --wbits 4 --groupsize 128**

...

Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Traceback (most recent call last):
  File "/home/dr/text-generation-webui/server.py", line 308, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/dr/text-generation-webui/modules/models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "/home/dr/text-generation-webui/modules/GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

**Comment by Priestru** [comment] 2023-04-08 00:05
Traceback (most recent call last):
  File "/mnt/c/Users/Yuuru/text-generation-webui/server.py", line 308, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/c/Users/Yuuru/text-generation-webui/modules/models.py", line 106, in load_model
    from modules.llamacpp_model_alternative import LlamaCppModel
  File "/mnt/c/Users/Yuuru/text-generation-webui/modules/llamacpp_model_alternative.py", line 9, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

Hard to believe but i got this error again on FRESH WSL

**Comment by sfxworks** [comment] 2023-04-08 01:33
> Until ooba fix it, we can help themselves by reversing this commit to models.py:
> 
> [03cb44f](https://github.com/oobabooga/text-generation-webui/commit/03cb44fc8ca24c6458dbd25c31acd1e8cbdfcde2)

Reverting this (llamacpp_model_alternative not even present anymore?) still yields this same issue, 


```
Loading elinas_alpaca-30b-lora-int4...
Traceback (most recent call last):
  File "/home/sam/git/text-generation-webui/server.py", line 276, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/sam/git/text-generation-webui/modules/models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "/home/sam/git/text-generation-webui/modules/GPTQ_loader.py", line 13, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
```

**Comment by jllllll** [comment] 2023-04-08 05:54
This error is caused by the temporary removal of llama-cpp-python as it requires a local compiler to compile it, which causes issues with the Windows one-click-installer.

We are currently waiting for the dev of llama-cpp-python to publish wheels for easy install.

If you have a compiler, then can enter this command to install llama-cpp-python:
`python -m pip install llama-cpp-python`

If you used the Windows one-click-installer, then open `micromamba-cmd.bat` to use that command.

**Comment by sfxworks** [comment] 2023-04-08 06:35
For anyone running an m10, https://discord.com/channels/1089972953506123937/1094128535616098385

**Comment by Priestru** [comment] 2023-04-08 13:47
> This error is caused by the temporary removal of llama-cpp-python as it requires a local compiler to compile it, which causes issues with the Windows one-click-installer.
> 
> We are currently waiting for the dev of llama-cpp-python to publish wheels for easy install.
> 
> If you have a compiler, then can enter this command to install llama-cpp-python: `python -m pip install llama-cpp-python==0.1.23`
> 
> If you used the Windows one-click-installer, then open `micromamba-cmd.bat` to use that command.
> 
> As per the instructions here: https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models#using-llamacpp-in-the-web-ui
> 
> The .bin model file's name must begin with `ggml`
> 
> The `llama_inference_offload` error is a separate issue that I don't know the cause of. Make sure that you have this folder structure: `\text-generation-webui\repositories\GPTQ-for-LLaMa` and that `llama_inference_offload.py` is in that folder.

used python -m pip install llama-cpp-python==0.1.23 in micromamba-cmd.bat but didnt help. Switched to use wsl for now.

**Comment by Enferlain** [comment] 2023-04-08 21:44
@jllllll 

Tried that, the error changed to

```
Loading gpt4-x-alpaca-13b-native-ggml-model-q4_0...
Traceback (most recent call last):
  File "D:\textgen\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\textgen\oobabooga-windows\text-generation-webui\modules\models.py", line 106, in load_model
    from modules.llamacpp_model_alternative import LlamaCppModel
  File "D:\textgen\oobabooga-windows\text-generation-webui\modules\llamacpp_model_alternative.py", line 9, in <module>
    from llama_cpp import Llama
  File "D:\textgen\oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "D:\textgen\oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 46, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "D:\textgen\oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 40, in _load_shared_library
    raise FileNotFoundError(f"Shared library with base name '{lib_base_name}' not found")
FileNotFoundError: Shared library with base name 'llama' not found
```

sadge

**Comment by Crimsonfart** [comment] 2023-04-09 00:01
From [jllllll](https://github.com/jllllll)

Here is how to install the requirements for llama.cpp models in webui easily:

    Download this archive here: https://github.com/abetlen/llama-cpp-python/suites/12105838837/artifacts/637822425
    Extract llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl from it and place it next to micromamba-cmd.bat
    Open micromamba-cmd.bat and enter this command:

python -m pip install llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl

If not on Windows, there are Linux wheels in that archive as well, though it is better to compile llama-cpp-python yourself if you can.

**Comment by Crimsonfart** [comment] 2023-04-09 00:04
This FIX worked for me! https://github.com/oobabooga/text-generation-webui/issues/912#issuecomment-1500961747

**Comment by kylehagin** [comment] 2023-04-19 01:42
> For anyone running a k80, https://discord.com/channels/1089972953506123937/1094128535616098385


> For anyone running a k80, https://discord.com/channels/1089972953506123937/1094128535616098385

Hi sfxworks, I have some k80s I want to get running with this.  Is this discord still active?

**Closed** 2023-04-23 10:28 UTC
Labels: bug

**Comment by sfxworks** [comment] 2023-04-23 12:05
Yep
