### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by one-pip** [oobabooga/text-generation-webui#5785] opened 2024-04-01 11:32 UTC
### Describe the bug

after i updated the webui,  here is the problem happened....

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\NEW_OOBA\text-generation-webui-main\server.py:21 in <module>                                                 │
│                                                                                                                      │
│    20 with RequestBlocker():                                                                                         │
│ ❱  21     from modules import gradio_hijack                                                                          │
│    22     import gradio as gr                                                                                        │
│                                                                                                                      │
│ D:\NEW_OOB\text-generation-webui-main\modules\gradio_hijack.py:9 in <module>                                   │
│                                                                                                                      │
│    8                                                                                                                 │
│ ❱  9 import gradio as gr                                                                                             │
│   10                                                                                                                 │
│                                                                                                                      │
│ D:\NEW_OOBA\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\__init__.py:3 in <module>   │
│                                                                                                                      │
│     2                                                                                                                │
│ ❱   3 import gradio._simple_templates                                                                                │
│     4 import gradio.image_utils                                                                                      │
│                                                                                                                      │
│ D:\NEW_OOBA\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\_simple_templates\__init__. │
│ py:1 in <module>                                                                                                     │
│                                                                                                                      │
│ ❱ 1 from .simpledropdown import SimpleDropdown                                                                       │
│   2 from .simpleimage import SimpleImage                                                                             │
│                                                                                                                      │
│ D:\NEW_OOBA\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\_simple_templates\simpledro │
│ pdown.py:6 in <module>                                                                                               │
│                                                                                                                      │
│     5                                                                                                                │
│ ❱   6 from gradio.components.base import FormComponent                                                               │
│     7 from gradio.events import Events                                                                               │
│                                                                                                                      │
│ D:\NEW_OOBA\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\components\__init__.py:40   │
│ in <module>                                                                                                          │
│                                                                                                                      │
│    39 from gradio.components.model3d import Model3D                                                                  │
│ ❱  40 from gradio.components.multimodal_textbox import MultimodalTextbox                                             │
│    41 from gradio.components.number import Number                                                                    │
│                                                                                                                      │
│ D:\NEW_OOBA\ext-generation-webui-main\installer_files\env\Lib\site-packages\gradio\components\multimodal_textb │
│ ox.py:34 in <module>                                                                                                 │
│                                                                                                                      │
│    33 @document()                                                                                                    │
│ ❱  34 class MultimodalTextbox(FormComponent):                                                                        │
│    35     """                                                                                                        │
│                                                                                                                      │
│ D:\NEW_OOBA\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\component_meta.py:198 in    │
│ __new__                                                                                                              │
│                                                                                                                      │
│   197         component_class = super().__new__(cls, name, bases, attrs)                                             │
│ ❱ 198         create_or_modify_pyi(component_class, name, events)                                                    │
│   199         return component_class                                                                                 │
│                                                                                                                      │
│ D:\NEW_OOBA\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\component_meta.py:92 in     │
│ create_or_modify_pyi                                                                                                 │
│                                                                                                                      │
│    91                                                                                                                │
│ ❱  92     source_code = source_file.read_text()                                                                      │
│    93                                                                                                                │
│                                                                                                                      │
│ D:\NEW_OOBA\text-generation-webui-main\installer_files\env\Lib\pathlib.py:1059 in read_text                     │
│                                                                                                                      │
│   1058         with self.open(mode='r', encoding=encoding, errors=errors) as f:                                      │
│ ❱ 1059             return f.read()                                                                                   │
│   1060                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence
请按任意键继续. . .

### Logs

```shell
above
```

### System Info

```shell
win11
I7
RTX4090
```

**Comment by Touch-Night** [comment] 2024-04-01 11:41
Reduplicate #5777

**Comment by AndyX-Net** [comment] 2024-04-01 12:45
> Try downgrading gradio to 4.21. Or update to 4.24

Thanks for callout....

**pip show gradio**
Name: gradio
Version: 4.23.0
Summary: Python library for easily interacting with trained machine learning models

**pip install gradio --upgrade**
Collecting gradio
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/88/45/8108a9af9348cc707bf30d2a85255c21121f6841dee00bf3e266a731141b/gradio-4.24.0-py3-none-any.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 8.7 MB/s eta 0:00:00
Installing collected packages: gradio
  Attempting uninstall: gradio
    Found existing installation: gradio 4.23.0
    Uninstalling gradio-4.23.0:
      Successfully uninstalled gradio-4.23.0
**Successfully installed gradio-4.24.0**

**Comment by one-pip** [comment] 2024-04-01 14:33
> > Try downgrading gradio to 4.21. Or update to 4.24
> 
> Thanks for callout....
> 
> **pip show gradio** Name: gradio Version: 4.23.0 Summary: Python library for easily interacting with trained machine learning models
> 
> **pip install gradio --upgrade** Collecting gradio Downloading https://pypi.tuna.tsinghua.edu.cn/packages/88/45/8108a9af9348cc707bf30d2a85255c21121f6841dee00bf3e266a731141b/gradio-4.24.0-py3-none-any.whl (17.1 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 8.7 MB/s eta 0:00:00 Installing collected packages: gradio Attempting uninstall: gradio Found existing installation: gradio 4.23.0 Uninstalling gradio-4.23.0: Successfully uninstalled gradio-4.23.0 **Successfully installed gradio-4.24.0**


C:\Users\Administrator>pip show gradio
Name: gradio
Version: 4.24.0
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:

I have updated to 4.24.0, but the same problem is still in there?

**Comment by Touch-Night** [comment] 2024-04-01 15:05
> > > Try downgrading gradio to 4.21. Or update to 4.24
> > 
> > 
> > Thanks for callout....
> > **pip show gradio** Name: gradio Version: 4.23.0 Summary: Python library for easily interacting with trained machine learning models
> > **pip install gradio --upgrade** Collecting gradio Downloading https://pypi.tuna.tsinghua.edu.cn/packages/88/45/8108a9af9348cc707bf30d2a85255c21121f6841dee00bf3e266a731141b/gradio-4.24.0-py3-none-any.whl (17.1 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 8.7 MB/s eta 0:00:00 Installing collected packages: gradio Attempting uninstall: gradio Found existing installation: gradio 4.23.0 Uninstalling gradio-4.23.0: Successfully uninstalled gradio-4.23.0 **Successfully installed gradio-4.24.0**
> 
> C:\Users\Administrator>pip show gradio Name: gradio Version: 4.24.0 Summary: Python library for easily interacting with trained machine learning models Home-page: Author:
> 
> I have updated to 4.24.0, but the same problem is still in there?

Gradio 4.24.0 works for me. If the issue resists, try downgrading it to 4.21.0.

**Comment by Kingbadger3d** [comment] 2024-04-01 15:15
Yep the code is major broken again, I'm getting upgrade errors saying there are unmerged files, which means you have to go through one by one merging them and hope they don't cause conflicts. You can load into oobabooga, but then after trying to load extensions it errors out and exits.

It's a dev problem again.

**Comment by Touch-Night** [comment] 2024-04-01 15:21
> Yep the code is major broken again, I'm getting upgrade errors saying there are unmerged files, which means you have to go through one by one merging them and hope they don't cause conflicts. You can load into oobabooga, but then after trying to load extensions it errors out and exits.
> 
> It's a dev problem again.

I haven't encountered any other issues besides gbk decode error, and both downgrading gradio to 4.21.0 and upgrading to 4.24.0 works for me. Have you modified any files tracked by git? You can try to `Revert local changes to repository files with "git reset --hard"` in update wizard.

**Comment by Kingbadger3d** [comment] 2024-04-01 15:25
I tried updateing a already workingsetup and it did this. So moved my models folder and extensions folder to another directory, wiped the whole install, git cloned from scratch, and the same thing happened. Non merged files, and if you have extensions activated loads them them errors out with:

16:25:03-136086 INFO     Loading the extension "coqui_tts"
[XTTS] Loading XTTS...
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
[XTTS] Done!
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\Textgen\text-generation-webui\server.py:255 in <module>                                                          │
│                                                                                                                     │
│   254         # Launch the web UI                                                                                   │
│ > 255         create_interface()                                                                                    │
│   256         while True:                                                                                           │
│                                                                                                                     │
│ E:\Textgen\text-generation-webui\server.py:156 in create_interface                                                  │
│                                                                                                                     │
│   155         extensions_module.create_extensions_tabs()  # Extensions tabs                                         │
│ > 156         extensions_module.create_extensions_block()  # Extensions block                                       │
│   157                                                                                                               │
│                                                                                                                     │
│ E:\Textgen\text-generation-webui\modules\extensions.py:199 in create_extensions_block                               │
│                                                                                                                     │
│   198                 extension, _ = row                                                                            │
│ > 199                 extension.ui()                                                                                │
│   200                                                                                                               │
│                                                                                                                     │
│ E:\Textgen\text-generation-webui\extensions\code_syntax_highlight\script.py:73 in ui                                │
│                                                                                                                     │
│    72         ''', visible=False)                                                                                   │
│ >  73         interface.load(None, None, None, _js=f'() => {{{js_data_proxy_loader+js_modules}                      │
│    74                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument '_js'

**Comment by Kingbadger3d** [comment] 2024-04-01 15:27
And if you try to use the update windows wizard, you get:


What would you like to do?

A) Update the web UI
B) Install/update extensions requirements
C) Revert local changes to repository files with "git reset --hard"
N) Nothing (exit)

Input> A


*******************************************************************
* Updating the local copy of the repository with "git pull"
*******************************************************************


error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Command '"E:\Textgen\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "E:\Textgen\text-generation-webui\installer_files\env" >nul && git pull --autostash' failed with exit status code '128'.

Exiting now.
Try running the start/update script again.

**Comment by Touch-Night** [comment] 2024-04-01 15:35
> I tried updateing a already workingsetup and it did this. So moved my models folder and extensions folder to another directory, wiped the whole install, git cloned from scratch, and the same thing happened. Non merged files, and if you have extensions activated loads them them errors out with:
> 
> 16:25:03-136086 INFO Loading the extension "coqui_tts" [XTTS] Loading XTTS...
> 
> > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
> > Using model: xtts
> > [XTTS] Done!
> > ┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
> > │ E:\Textgen\text-generation-webui\server.py:255 in                                                           │
> > │                                                                                                                     │
> > │   254         # Launch the web UI                                                                                   │
> > │ > 255         create_interface()                                                                                    │
> > │   256         while True:                                                                                           │
> > │                                                                                                                     │
> > │ E:\Textgen\text-generation-webui\server.py:156 in create_interface                                                  │
> > │                                                                                                                     │
> > │   155         extensions_module.create_extensions_tabs()  # Extensions tabs                                         │
> > │ > 156         extensions_module.create_extensions_block()  # Extensions block                                       │
> > │   157                                                                                                               │
> > │                                                                                                                     │
> > │ E:\Textgen\text-generation-webui\modules\extensions.py:199 in create_extensions_block                               │
> > │                                                                                                                     │
> > │   198                 extension, _ = row                                                                            │
> > │ > 199                 extension.ui()                                                                                │
> > │   200                                                                                                               │
> > │                                                                                                                     │
> > │ E:\Textgen\text-generation-webui\extensions\code_syntax_highlight\script.py:73 in ui                                │
> > │                                                                                                                     │
> > │    72         ''', visible=False)                                                                                   │
> > │ >  73         interface.load(None, None, None, _js=f'() => {{{js_data_proxy_loader+js_modules}                      │
> > │    74                                                                                                               │
> > └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> > TypeError: EventListener._setup..event_trigger() got an unexpected keyword argument '_js'

That would be a new issue. Maybe code_syntax_highlight extension is not compatible with gradio 4.2x.
For me, I can load [more_translators](https://github.com/Touch-Night/more_translators), openai and gallery extensions without issue.

**Comment by Kingbadger3d** [comment] 2024-04-01 15:44
Tried to Revert local changes to repository files, nada, same issue.

**Comment by Touch-Night** [comment] 2024-04-01 15:52
> Tried to Revert local changes to repository files, nada, same issue.

I tried [code_syntax_highlight](https://github.com/DavG25/text-generation-webui-code_syntax_highlight) and met the same issue. Yes, [1a7c027](https://github.com/oobabooga/text-generation-webui/commit/1a7c027386f43b84f3ca3b0ff04ca48d861c2d7a) breaks some extensions. Plus, for newly installed extensions (code_syntax_highlight this time), I get `AttributeError: module 'extensions' has no attribute 'text-generation-webui-code_syntax_highlight'` when click `Save UI defaults to settings.yaml` button (Similar as #5779 ).

**Comment by Kingbadger3d** [comment] 2024-04-01 15:53
yeah I tried down grading gradio to 4.21.0 and still same issue

**Comment by Kingbadger3d** [comment] 2024-04-01 15:53
lets hope they fix it soon

**Comment by Touch-Night** [comment] 2024-04-01 15:58
> I tried updateing a already workingsetup and it did this. So moved my models folder and extensions folder to another directory, wiped the whole install, git cloned from scratch, and the same thing happened. Non merged files, and if you have extensions activated loads them them errors out with:
> 
> 16:25:03-136086 INFO Loading the extension "coqui_tts" [XTTS] Loading XTTS...
> 
> > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
> > Using model: xtts
> > [XTTS] Done!
> > ┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
> > │ E:\Textgen\text-generation-webui\server.py:255 in                                                           │
> > │                                                                                                                     │
> > │   254         # Launch the web UI                                                                                   │
> > │ > 255         create_interface()                                                                                    │
> > │   256         while True:                                                                                           │
> > │                                                                                                                     │
> > │ E:\Textgen\text-generation-webui\server.py:156 in create_interface                                                  │
> > │                                                                                                                     │
> > │   155         extensions_module.create_extensions_tabs()  # Extensions tabs                                         │
> > │ > 156         extensions_module.create_extensions_block()  # Extensions block                                       │
> > │   157                                                                                                               │
> > │                                                                                                                     │
> > │ E:\Textgen\text-generation-webui\modules\extensions.py:199 in create_extensions_block                               │
> > │                                                                                                                     │
> > │   198                 extension, _ = row                                                                            │
> > │ > 199                 extension.ui()                                                                                │
> > │   200                                                                                                               │
> > │                                                                                                                     │
> > │ E:\Textgen\text-generation-webui\extensions\code_syntax_highlight\script.py:73 in ui                                │
> > │                                                                                                                     │
> > │    72         ''', visible=False)                                                                                   │
> > │ >  73         interface.load(None, None, None, _js=f'() => {{{js_data_proxy_loader+js_modules}                      │
> > │    74                                                                                                               │
> > └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> > TypeError: EventListener._setup..event_trigger() got an unexpected keyword argument '_js'

For this issue, try editing `_js` in `extensions\code_syntax_highlight\script.py:73` to `js`. gallery, openai, whisper_stt extensions used this approach in the update.

**Comment by berkut1** [comment] 2024-04-01 21:57
I just updated it and everything works correct.
I suppose the problem is in one of your plugins/extension. I recommend to disable all of them.

**Comment by HonZuna** [comment] 2024-04-01 22:02
Same issue no plugins or extensions installed.

**Comment by berkut1** [comment] 2024-04-01 22:41
@HonZuna did you try double time to run update.bat script with selecting the option "A"?

**Comment by one-pip** [comment] 2024-04-02 02:23
> > > > Try downgrading gradio to 4.21. Or update to 4.24
> > > 
> > > 
> > > Thanks for callout....
> > > **pip show gradio** Name: gradio Version: 4.23.0 Summary: Python library for easily interacting with trained machine learning models
> > > **pip install gradio --upgrade** Collecting gradio Downloading https://pypi.tuna.tsinghua.edu.cn/packages/88/45/8108a9af9348cc707bf30d2a85255c21121f6841dee00bf3e266a731141b/gradio-4.24.0-py3-none-any.whl (17.1 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 8.7 MB/s eta 0:00:00 Installing collected packages: gradio Attempting uninstall: gradio Found existing installation: gradio 4.23.0 Uninstalling gradio-4.23.0: Successfully uninstalled gradio-4.23.0 **Successfully installed gradio-4.24.0**
> > 
> > 
> > C:\Users\Administrator>pip show gradio Name: gradio Version: 4.24.0 Summary: Python library for easily interacting with trained machine learning models Home-page: Author:
> > I have updated to 4.24.0, but the same problem is still in there?
> 
> Gradio 4.24.0 works for me. If the issue resists, try downgrading it to 4.21.0.

4.21.0 is the same problem.......................today i have updated again, but the problem is still not solved.

**Comment by Touch-Night** [comment] 2024-04-02 02:31
> 
> 4.21.0 is the same problem.......................today i have updated again, but the problem is still not solved.
That's weird. Are you sure it's still UnicodeDecodeError? Are you sure you pip install in `cmd_windows.bat` to update or downgrade gradio in TextGenWebui's environment, instead of doing so in your base environment?

**Comment by a442509097** [comment] 2024-04-02 14:59
Me too,  even I delete all the files and re-download, same problem.

**Comment by Kingbadger3d** [comment] 2024-04-02 15:03
Also, how do we use LLM web search? it doesn't seem to work?

**Comment by HonZuna** [comment] 2024-04-02 18:26
> @HonZuna did you try double time to run update.bat script with selecting the option "A"?

That actually helped. Thank you !

**Comment by tanaous** [comment] 2024-04-05 16:30
> ## Me too, even I delete all the files and re-download, same problem.
> Okay, I've solved it, using I:\text-generation-webui\cmd_windows.bat, pip install gradio --upgrade

Thank you !   it works now

**Closed** 2024-04-07 06:04 UTC
Labels: bug
